PREFIX cap: <http://data.europa.eu/w21/2c930c7b-5e2f-4954-8522-bd3411339d6c/extension/cap#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cccev: <https://data.europe.eu/semanticassets/ns/cv/cccev_v2.0.0#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?input (concat(?givenName, " ", ?familyName) as ?agent) ?source ?target ?winner ?value (str(?crit)as ?criterion)  ?maxscore
FROM cap:
WHERE {
    ?input rdf:type cap:InputValue ;
       cap:comparesSourceThing ?source ;
       cap:comparesWithTargetThing ?target ;
       cap:hasBetterCandidate ?winner ;
       cap:hasNumericValue ?value ;
       cap:isProvidedBy ?agentObj;
       cap:refersToCriterion ?cObj .
    ?cObj cccev:hasName ?crit ;
               cap:hasMaximumScore ?maxscore .
    ?agentObj foaf:givenName ?givenName ;
              foaf:familyName ?familyName .

} ORDER BY ?agent
